# Generated by Django 2.2.16 on 2022-08-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_users_app_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Superuser'), (1, 'Admin'), (2, 'Moderator'), (3, 'User')], default=3),
        ),
    ]
