# Generated by Django 2.2.16 on 2022-08-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_model_bio_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=5, verbose_name='Код верификации'),
        ),
    ]
