# Generated by Django 2.2.16 on 2022-08-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_model_confirmation_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
